name:                atlas
version:             0.1.0.0
github:              "Anviking/Atlas"
license:             MIT
author:              "Johannes Lund"
maintainer:          "anviking@me.com"
copyright:           "2019 Johannes Lund"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Anviking/Atlas#readme>

dependencies:
- base >= 4.7 && < 5
- hlint
- aeson
- wreq
- bytestring
- lens
- haskell-src-exts
- time
- process
- attoparsec

library:
  source-dirs: src

executables:
  atlas-check:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atlas

tests:
  atlas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atlas
    - hspec
